version: '3.8'

services:

  conductor-service:
    image: conductoross/conductor-standalone:3.15.0
    container_name: conductor-service
    restart: unless-stopped
    ports:
      - "${CONDUCTOR_API_PORT}:${DEFAULT_SERVER_PORT}"
      - "${CONDUCTOR_UI_PORT}:${CONDUCTOR_UI_PORT}"
    volumes:
      - conductor_data:/app/data
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${DEFAULT_SERVER_PORT}/api/admin/config || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - raikiri-cloud-saga-net

  saga-manager-api:
    build: ./saga-manager-api
    container_name: saga-manager-api
    ports:
      - "${SAGA_MANAGER_API_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - SERVER_PORT=${DEFAULT_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-saga-manager:${DEFAULT_POSTGRES_PORT}/${SAGA_MANAGER_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DEFAULT_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - CONDUCTOR_API=http://conductor-service:${DEFAULT_SERVER_PORT}/api
    depends_on:
      conductor-service:
        condition: service_healthy
      postgres-saga-manager:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      - SERVER_PORT=${EUREKA_SERVER_PORT}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
      conductor-service:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - SERVER_PORT=${DEFAULT_SERVER_PORT}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
      conductor-service:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

  postgres-restaurant:
    image: postgres:16-alpine
    container_name: postgres-restaurant
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${RESTAURANT_DATABASE_NAME}
      POSTGRES_USER: ${DEFAULT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEFAULT_POSTGRES_PASSWORD}
    ports:
      - "${RESTAURANT_POSTGRES_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - pg_restaurant_data:/var/lib/postgresql/data
    networks:
      - raikiri-cloud-saga-net

  postgres-courier:
    image: postgres:16-alpine
    container_name: postgres-courier
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${COURIER_DATABASE_NAME}
      POSTGRES_USER: ${DEFAULT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEFAULT_POSTGRES_PASSWORD}
    ports:
      - "${COURIER_POSTGRES_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - pg_courier_data:/var/lib/postgresql/data
    networks:
      - raikiri-cloud-saga-net

  postgres-payment:
    image: postgres:16-alpine
    container_name: postgres-payment
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PAYMENT_DATABASE_NAME}
      POSTGRES_USER: ${DEFAULT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEFAULT_POSTGRES_PASSWORD}
    ports:
      - "${PAYMENT_POSTGRES_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - pg_payment_data:/var/lib/postgresql/data
    networks:
      - raikiri-cloud-saga-net

  postgres-notification:
    image: postgres:16-alpine
    container_name: postgres-notification
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NOTIFICATION_DATABASE_NAME}
      POSTGRES_USER: ${DEFAULT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEFAULT_POSTGRES_PASSWORD}
    ports:
      - "${NOTIFICATION_POSTGRES_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - pg_notification_data:/var/lib/postgresql/data
    networks:
      - raikiri-cloud-saga-net

  postgres-saga-manager:
    image: postgres:16-alpine
    container_name: postgres-saga-manager
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SAGA_MANAGER_DATABASE_NAME}
      POSTGRES_USER: ${DEFAULT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEFAULT_POSTGRES_PASSWORD}
    ports:
      - "${SAGA_MANAGER_POSTGRES_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - pg_saga_manager_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - raikiri-cloud-saga-net

  restaurant-api:
    build: ./restaurant-api
    container_name: restaurant-api
    ports:
      - "${RESTAURANT_API_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - SERVER_PORT=${DEFAULT_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-restaurant:${DEFAULT_POSTGRES_PORT}/${RESTAURANT_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DEFAULT_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
      conductor-service:
        condition: service_healthy
      eureka-server:
        condition: service_started
      postgres-restaurant:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

  courier-api:
    build: ./courier-api
    container_name: courier-api
    ports:
      - "${COURIER_API_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - SERVER_PORT=${DEFAULT_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-courier:${DEFAULT_POSTGRES_PORT}/${COURIER_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DEFAULT_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
      conductor-service:
        condition: service_healthy
      eureka-server:
        condition: service_started
      postgres-courier:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

  payment-api:
    build: ./payment-api
    container_name: payment-api
    ports:
      - "${PAYMENT_API_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - SERVER_PORT=${DEFAULT_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:${DEFAULT_POSTGRES_PORT}/${PAYMENT_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DEFAULT_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
      conductor-service:
        condition: service_healthy
      eureka-server:
        condition: service_started
      postgres-payment:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

  notification-api:
    build: ./notification-api
    container_name: notification-api
    ports:
      - "${NOTIFICATION_API_PORT}:${DEFAULT_SERVER_PORT}"
    environment:
      - SERVER_PORT=${DEFAULT_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-notification:${DEFAULT_POSTGRES_PORT}/${NOTIFICATION_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DEFAULT_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
      conductor-service:
        condition: service_healthy
      eureka-server:
        condition: service_started
      postgres-notification:
        condition: service_started
    networks:
      - raikiri-cloud-saga-net

volumes:
  pg_restaurant_data:
  pg_courier_data:
  pg_payment_data:
  pg_notification_data:
  pg_saga_manager_data:
  conductor_data:

networks:
  raikiri-cloud-saga-net:
    driver: bridge